CREATE
  DATABASE db;
CREATE
  DATABASE development;
CREATE
  DATABASE testing;

GRANT ALL PRIVILEGES ON DATABASE
  db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE
  development TO postgres;
GRANT ALL PRIVILEGES ON DATABASE
  testing TO postgres;
