CREATE
  DATABASE db;
CREATE
  DATABASE db_development;
CREATE
  DATABASE db_testing;

GRANT ALL PRIVILEGES ON DATABASE
  db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE
  db_development TO postgres;
GRANT ALL PRIVILEGES ON DATABASE
  db_testing TO postgres;
